from .sedes_pntlla import sedes_pantalla
from .centrosacopio_pntlla import centrosacopio_panatlla
from .catalogo_materiales_pntlla import catalogo_materiales_pantalla
from .crear_transaccion_pntlla import crear_transaccion_pntlla