
from .catalogo_materiales_logica_pntlla import crear_material,actualizar_lista
from .centrosacopio_logica_pntlla import crear_centro_acopio
from .sedes_logica_pntlla import crear_sede,limpiar_campos
from .auten_logica_pntlla import iniciar_sesion, cerrar_sesion
from .historial_trans_logica_pantlla import ingresa_datos_transacciones,buscar_transacciones

from .historial_trans_logica_pantlla import ingresa_datos_transacciones,buscar_transacciones,mostrar_transaccion_detalles,close_window
from .mostrar_detalles_logica_pntlla import anular_transaccion